USE_COMPILER = True

#ROOT_URL = 'http://stanford.edu/~cpiech/Elimu'
ROOT_URL = 'localhost:8000/'

MAX_CORNER_SIZE = 160
KAREL_NORTH = 0
KAREL_EAST = 1
KAREL_SOUTH = 2
KAREL_WEST = 3

KAREL_SMALL_SIZE = 30
KAREL_TINY_SIZE = 19

BORDER_SIZE = 2
CROSS_FRACTION = 0.25
MIN_CROSS_SIZE = 5

BEEPER_SIZE_FRACTION = 0.85
BEEPER_FILL_COLOR = "#12C4FF"
BEEPER_LABEL_FRACTION = 0.3
BEEPER_LABEL_MIN_SIZE = 6
BEEPER_LABEL_MAX_SIZE = 18
BEEPER_LABEL_FONT = "sans-serif"
BEEPER_LABEL_DY = 0.2
MIN_BEEPER_LABEL_SIZE = 20
WALL_THICKNESS_FRACTION = 0.1
BACKGROUND_COLOR = 'white'

MIN_IDE_WIDTH = 850
HEADER_HEIGHT = 50
PROGRAM_HEADER_HEIGHT = 200
BUTTON_BAR_HEIGHT = 60
PADDING = 24
LEARN_ASPECT_RATIO = 1.33
COMMENT_WIDTH = 400

MAX_ACTIONS = 1000
